# Generated by Django 3.0.5 on 2020-04-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('institution_type', models.CharField(choices=[('F', 'Fundacja'), ('O', 'Organizacja pozarządowa'), ('L', 'Zbiórka lokalna')], default='F', max_length=20)),
                ('categories', models.ManyToManyField(to='charity.Category')),
            ],
        ),
    ]
